name: Build APK Automático
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar Buildozer e dependências
      run: |
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y git unzip openjdk-17-jdk zlib1g-dev

    - name: Rodar Buildozer
      run: |
        buildozer init
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: APK-Gerado
        path: bin/*.apk
