name: Build APK with Buildozer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90  # Aumentado para builds complexos

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          zip \
          unzip \
          openjdk-17-jdk \
          zlib1g-dev \
          ccache \
          git \
          libncurses5 \
          libtinfo5 \
          libxml2-dev \
          libxslt-dev

        python -m pip install --upgrade pip wheel setuptools
        pip install buildozer==1.5.0 cython==0.29.33 virtualenv appdirs

    - name: Set up Android SDK
      run: |
        mkdir -p ~/android-sdk/cmdline-tools/latest
        cd ~/android-sdk/cmdline-tools/latest
        
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        rm commandlinetools-linux-9477386_latest.zip

        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV

        yes | sdkmanager --licenses > /dev/null
        sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-33" "ndk;25.1.8937393"

    - name: Prepare build environment
      run: |
        mkdir -p $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        
        # Cria um buildozer.spec completo se não existir
        if [ ! -f buildozer.spec ]; then
          cat <<EOF > buildozer.spec
[app]
title = BuffetCalculator
package.name = buffetcalculator
package.domain = org.yourdomain
version = 1.0.0
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
requirements = python3,kivy==2.2.1
android.api = 33
android.minapi = 21
android.ndk_path = $HOME/android-sdk/ndk/25.1.8937393
android.sdk_path = $HOME/android-sdk
android.arch = arm64-v8a

[buildozer]
log_level = 2
warn_on_root = 1
EOF
        fi

    - name: Run Buildozer
      run: |
        cd $GITHUB_WORKSPACE/build
        
        # Limpa builds anteriores
        buildozer android clean
        
        # Build com log detalhado
        buildozer -v android debug 2>&1 | tee build.log
        
        # Verifica se o APK foi gerado
        if [ ! -f bin/*.apk ]; then
          echo "::error::Build failed - APK not generated"
          tail -n 100 build.log
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: $GITHUB_WORKSPACE/build/bin/*.apk
