[app]

# (str) Title of your application
title = MyApp

# (str) Package name
package.name = myapp

# (str) Package domain
package.domain = org.test

# (str) Version of your application
version = 1.0.0  # Aqui você define a versão da sua app

# (str) Application source directory
source.dir = .

# (list) Application requirements
requirements = python3,kivy

# (str) Android NDK path
android.ndk_path = /home/runner/android-sdk/ndk/25.1.8937393

# (str) Android SDK path
android.sdk_path = /home/runner/android-sdk

# (str) Python-for-android directory
android.p4a.source_dir = /home/runner/work/BuffetCalculatorPRO/BuffetCalculatorPRO/build/.buildozer/android/platform/python-for-android

# (bool) Enable Android NDK for the build
android.ndk = True

# (str) Minimum API level for Android
android.minapi = 21

# Outros parâmetros relevantes do seu app
