name: Build APK - Solução Definitiva

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04  # Versão mais estável
    timeout-minutes: 90

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          zip \
          unzip \
          openjdk-8-jdk \
          zlib1g-dev \
          ccache \
          git \
          libncurses5 \
          libtinfo5

        pip install --upgrade pip==20.3.4
        pip install buildozer==1.2.0
        pip install cython==0.29.21
        pip install appdirs

    - name: Setup Android SDK (Modo Verificado)
      run: |
        mkdir -p ~/android-sdk
        cd ~/android-sdk
        
        # Baixar pacote completo do SDK
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip
        rm sdk-tools-linux-4333796.zip
        
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
        
        yes | sdkmanager --licenses > /dev/null
        sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30" "ndk-bundle"

    - name: Prepare Build Environment
      run: |
        mkdir -p $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        
        # Configuração garantida
        cat <<EOF > buildozer.spec
[app]
title = BuffetCalculator
package.name = buffetcalculator
package.domain = org.yourdomain
version = 1.0.0
source.dir = ..
source.include_exts = py,png,jpg,kv,atlas
requirements = python3,kivy==2.0.0
android.api = 30
android.minapi = 21
android.sdk_path = $HOME/android-sdk
android.ndk_path = $HOME/android-sdk/ndk-bundle
android.ndk_version = 21.3.6528147
android.arch = armeabi-v7a  # Arquitetura mais compatível

[buildozer]
log_level = 2
warn_on_root = 1
EOF

    - name: Run Buildozer (Completo)
      run: |
        cd $GITHUB_WORKSPACE/build
        
        # Limpeza completa
        buildozer android clean 2>&1 | tee build.log
        
        # Build com verificação
        if ! buildozer -v android debug 2>&1 | tee -a build.log; then
          echo "::error::Build failed!"
          echo "=== Últimas 100 linhas do log ==="
          tail -n 100 build.log
          exit 1
        fi
        
        # Verificação final
        if [ ! -f bin/*.apk ]; then
          echo "::error::APK não gerado!"
          echo "=== Conteúdo do diretório bin/ ==="
          ls -la bin/
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: buffet-calculator-apk
        path: $GITHUB_WORKSPACE/build/bin/*.apk
