name: Build APK - Solução Garantida

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 120

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Versão mais estável

    - name: Setup Environment
      run: |
        # Configuração do sistema
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          zip \
          unzip \
          openjdk-8-jdk \
          zlib1g-dev
        
        # Versões exatas que funcionam
        python3 -m pip install --upgrade pip==19.3.1
        pip install buildozer==1.2.0 cython==0.29.19 virtualenv==16.7.10

    - name: Install Android SDK (Método Alternativo)
      run: |
        mkdir -p ~/android-sdk
        cd ~/android-sdk
        
        # Download do SDK completo
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip
        rm sdk-tools-linux-4333796.zip
        
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
        
        # Instalação mínima necessária
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses > /dev/null
        $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "build-tools;28.0.3" "platforms;android-28" "ndk-bundle"

    - name: Prepare Build
      run: |
        mkdir -p ~/build
        cd ~/build
        
        # Configuração infalível
        cat <<EOF > buildozer.spec
[app]
title = BuffetCalculator
package.name = buffetcalculator
package.domain = org.djcarlamorim
version = 1.0.0
source.dir = $GITHUB_WORKSPACE
source.include_exts = py,png,jpg,kv,atlas
requirements = python3,kivy==1.11.1
android.api = 28
android.minapi = 21
android.sdk_path = $HOME/android-sdk
android.ndk_path = $HOME/android-sdk/ndk-bundle
android.arch = armeabi-v7a
orientation = portrait

[buildozer]
log_level = 2
EOF

    - name: Run Buildozer
      run: |
        cd ~/build
        
        # Limpeza completa
        buildozer android clean > build.log 2>&1
        
        # Build com timeout
        timeout 60m buildozer -v android debug >> build.log 2>&1 || :
        
        # Análise do resultado
        if [ ! -f bin/*.apk ]; then
          echo "::error::Build failed! Last 50 lines:"
          tail -n 50 build.log
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: buffet-calculator-apk
        path: ~/build/bin/*.apk
