name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          zip \
          unzip \
          openjdk-8-jdk

        pip install --upgrade pip
        pip install buildozer

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33  # Ou versão desejada
        build-tools: 30.0.3
        ndk-version: 21.3.6528147

    - name: Build APK with Buildozer
      run: |
        # Certifique-se de estar no diretório correto onde o buildozer.spec está localizado
        cd $GITHUB_WORKSPACE  # Certifique-se de que o diretório está correto
        buildozer -v android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: buffet-calculator-pro-apk
        path: bin/*.apk
