name: Build APK with Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Docker
      run: |
        # Cria estrutura básica se não existir
        mkdir -p build
        [ -f build/buildozer.spec ] || cat <<EOF > build/buildozer.spec
[app]
title = MyApp
package.name = myapp
package.domain = org.example
version = 1.0.0
source.dir = .
requirements = python3,kivy==2.0.0
android.api = 30
android.minapi = 21

[buildozer]
log_level = 2
EOF

        # Executa o build usando container testado
        docker run --rm \
          -v "$PWD":/home/user/hostcwd \
          -v "$HOME/.buildozer":/home/user/.buildozer \
          -v "$HOME/.android":/home/user/.android \
          -e P4A_RELEASE_KEYSTORE=/home/user/hostcwd/build/keystore.jks \
          -e P4A_RELEASE_KEYSTORE_PASSWD=android \
          -e P4A_RELEASE_KEYALIAS_PASSWD=android \
          -e P4A_RELEASE_KEYALIAS=key \
          kivy/buildozer:1.2.0 \
          buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: build/bin/*.apk
