jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          zip \
          unzip \
          openjdk-17-jdk \
          zlib1g-dev \
          ccache \
          git \
          libncurses5 \
          libtinfo5

    - name: Cria diretório para o python-for-android se não existir
      run: |
        mkdir -p $GITHUB_WORKSPACE/build/.buildozer/android/platform/python-for-android

    - name: Clonar o repositório python-for-android
      run: |
        cd $GITHUB_WORKSPACE/build/.buildozer/android/platform
        git clone https://github.com/kivy/python-for-android.git

    - name: Instalar dependências do python-for-android
      run: |
        cd $GITHUB_WORKSPACE/build/.buildozer/android/platform/python-for-android
        pip install -r requirements.txt

    - name: Run Buildozer
      run: |
        cd $GITHUB_WORKSPACE/build
        buildozer android debug
