name: Build APK BuffetCalculatorPRO

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git unzip openjdk-8-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.33

    - name: Download Apache Ant manually
      run: |
        wget https://downloads.apache.org/ant/binaries/apache-ant-1.10.12-bin.tar.gz -O ant.tar.gz
        tar -xzf ant.tar.gz
        sudo mv apache-ant-1.10.12 /opt/ant
        echo "ANT_HOME=/opt/ant" >> $GITHUB_ENV
        echo "/opt/ant/bin" >> $GITHUB_PATH

    - name: Verify Apache Ant installation
      run: |
        ant -version

    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.android/licenses.cfg

    - name: Run Buildozer
      env:
        BUILDOVER_SKIP_SDK_CHECK: 1
        ANT_HOME: /opt/ant
      run: |
        buildozer init
        buildozer -v android debug

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: buffet-calculator-pro-apk
        path: bin/*.apk
