name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          zip \
          unzip \
          openjdk-8-jdk

        pip install --upgrade pip
        pip install buildozer
        pip install cython  # Instalar Cython

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33  # Ou versão desejada
        build-tools: 30.0.3
        ndk-version: 21.3.6528147

    - name: Accept SDK Licenses and Install build-tools and Aidl
      run: |
        # Aceitar as licenças
        yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses
        # Instalar o build-tools e Aidl
        $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;30.0.3"
        $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platform-tools"
        $ANDROID_HOME/cmdline-tools/bin/sdkmanager "android-33"  # Ou versão que você deseja
        # Verificar se Aidl está presente
        $ANDROID_HOME/platform-tools/adb version

    - name: Change to windows_build directory and run Buildozer
      run: |
        cd $GITHUB_WORKSPACE/windows_build  # Muda para o diretório correto
        buildozer -v android debug  # Executa o buildozer para gerar o APK

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: buffet-calculator-pro-apk
        path: windows_build/bin/*.apk
